// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SmartRental.Data;

#nullable disable

namespace SmartRental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003120000_AddDanhGia")]
    partial class AddDanhGia
    {
    }
}
