// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRental.Data;

#nullable disable

namespace SmartRental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261002033820_AddTienNghi")]
    partial class AddTienNghi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartRental.Models.PhongTienNghi", b =>
                {
                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiId")
                        .HasColumnType("int");

                    b.HasKey("PhongtroId", "TienNghiId");

                    b.HasIndex("TienNghiId");

                    b.ToTable("PhongTienNghis");
                });

            modelBuilder.Entity("SmartRental.Models.Phongtro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Phongtros");
                });

            modelBuilder.Entity("SmartRental.Models.TienNghi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TienNghis");
                });

            modelBuilder.Entity("SmartRental.Models.PhongTienNghi", b =>
                {
                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("PhongTienNghis")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.TienNghi", "TienNghi")
                        .WithMany("PhongTienNghis")
                        .HasForeignKey("TienNghiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phongtro");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("SmartRental.Models.Phongtro", b =>
                {
                    b.Navigation("PhongTienNghis");
                });

            modelBuilder.Entity("SmartRental.Models.TienNghi", b =>
                {
                    b.Navigation("PhongTienNghis");
                });
#pragma warning restore 612, 618
        }
    }
}
