// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRental.Data;

#nullable disable

namespace SmartRental.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009010340_AddSoNguoiToiDa")]
    partial class AddSoNguoiToiDa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartRental.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartRental.Models.CuocTroChuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuTroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PhongtroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuTroId");

                    b.HasIndex("PhongtroId");

                    b.HasIndex("NguoiThueId", "ChuTroId")
                        .IsUnique();

                    b.ToTable("CuocTroChuyens");
                });

            modelBuilder.Entity("SmartRental.Models.DanhGia", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PhongtroId");

                    b.HasIndex("NgayDanhGia");

                    b.HasIndex("PhongtroId");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("SmartRental.Models.LichSuXem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LanXemCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanXem")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PhongtroId");

                    b.HasIndex("LanXemCuoi");

                    b.HasIndex("PhongtroId");

                    b.ToTable("LichSuXems");
                });

            modelBuilder.Entity("SmartRental.Models.LichXemPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuTroId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ThoiGianXem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongtroId");

                    b.HasIndex("ChuTroId", "TrangThai", "ThoiGianXem");

                    b.ToTable("LichXemPhongs");
                });

            modelBuilder.Entity("SmartRental.Models.PhongTienNghi", b =>
                {
                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<int>("TienNghiId")
                        .HasColumnType("int");

                    b.HasKey("PhongtroId", "TienNghiId");

                    b.HasIndex("TienNghiId");

                    b.ToTable("PhongTienNghis");
                });

            modelBuilder.Entity("SmartRental.Models.Phongtro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongPhong")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Phongtros");
                });

            modelBuilder.Entity("SmartRental.Models.PhongtroHinhAnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAnhChinh")
                        .HasColumnType("bit");

                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongtroId", "ThuTu");

                    b.ToTable("PhongtroHinhAnhs");
                });

            modelBuilder.Entity("SmartRental.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DaDoc", "NgayTao");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("SmartRental.Models.TienNghi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTienNghi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TienNghis");
                });

            modelBuilder.Entity("SmartRental.Models.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocTroChuyenId")
                        .HasColumnType("int");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiTinNhan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGuiId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PhongtroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("PhongtroId");

                    b.HasIndex("CuocTroChuyenId", "NgayGui");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("SmartRental.Models.YeuThich", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhongtroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "PhongtroId");

                    b.HasIndex("PhongtroId");

                    b.ToTable("YeuThichs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRental.Models.CuocTroChuyen", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", "ChuTro")
                        .WithMany()
                        .HasForeignKey("ChuTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("CuocTroChuyens")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChuTro");

                    b.Navigation("NguoiThue");

                    b.Navigation("Phongtro");
                });

            modelBuilder.Entity("SmartRental.Models.DanhGia", b =>
                {
                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("DanhGias")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", "User")
                        .WithMany("DanhGias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phongtro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRental.Models.LichSuXem", b =>
                {
                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("LichSuXems")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", "User")
                        .WithMany("LichSuXems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phongtro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRental.Models.LichXemPhong", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", "ChuTro")
                        .WithMany()
                        .HasForeignKey("ChuTroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", "NguoiThue")
                        .WithMany()
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("LichXemPhongs")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuTro");

                    b.Navigation("NguoiThue");

                    b.Navigation("Phongtro");
                });

            modelBuilder.Entity("SmartRental.Models.PhongTienNghi", b =>
                {
                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("PhongTienNghis")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.TienNghi", "TienNghi")
                        .WithMany("PhongTienNghis")
                        .HasForeignKey("TienNghiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phongtro");

                    b.Navigation("TienNghi");
                });

            modelBuilder.Entity("SmartRental.Models.Phongtro", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", "Owner")
                        .WithMany("Phongtros")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SmartRental.Models.PhongtroHinhAnh", b =>
                {
                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phongtro");
                });

            modelBuilder.Entity("SmartRental.Models.ThongBao", b =>
                {
                    b.HasOne("SmartRental.Models.ApplicationUser", "User")
                        .WithMany("ThongBaos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRental.Models.TinNhan", b =>
                {
                    b.HasOne("SmartRental.Models.CuocTroChuyen", "CuocTroChuyen")
                        .WithMany("TinNhans")
                        .HasForeignKey("CuocTroChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("TinNhans")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CuocTroChuyen");

                    b.Navigation("NguoiGui");

                    b.Navigation("Phongtro");
                });

            modelBuilder.Entity("SmartRental.Models.YeuThich", b =>
                {
                    b.HasOne("SmartRental.Models.Phongtro", "Phongtro")
                        .WithMany("YeuThichs")
                        .HasForeignKey("PhongtroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRental.Models.ApplicationUser", "User")
                        .WithMany("YeuThichs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phongtro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRental.Models.ApplicationUser", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("LichSuXems");

                    b.Navigation("Phongtros");

                    b.Navigation("ThongBaos");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("SmartRental.Models.CuocTroChuyen", b =>
                {
                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("SmartRental.Models.Phongtro", b =>
                {
                    b.Navigation("CuocTroChuyens");

                    b.Navigation("DanhGias");

                    b.Navigation("HinhAnhs");

                    b.Navigation("LichSuXems");

                    b.Navigation("LichXemPhongs");

                    b.Navigation("PhongTienNghis");

                    b.Navigation("TinNhans");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("SmartRental.Models.TienNghi", b =>
                {
                    b.Navigation("PhongTienNghis");
                });
#pragma warning restore 612, 618
        }
    }
}
